title: 'Radio Aktywne'
default_lang: en
author:
  name: 'Maksymilian Szczepańczyk'
  email: maksymilian@paga.gg
taxonomies:
  - category
  - tag
metadata:
  description: 'Radio Aktywne - studenckie radio Politechniki Warszawskiej'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
