title: Default
'@extends':
   type: default
   context: blueprints://pages

form:
   fields:
      tabs:
         type: tabs
         active: 1

         fields:
            content:
               fields:
                  display_image:
                     type: file
                     label: Obrazek
                     destination: 'self@'
                     random_name: true
                     accept:
                        - 'image/*'
                  audio_attach:
                     type: file
                     label: Audio
                     destination: 'self@'
                     random_name: true
                     accept:
                        - 'audio/*'
